(переменная) = (полная переменная) | (компонента переменной)
(полная переменная) = (имя переменной)
(имя переменной) = (имя)
(имя) = (буква) {(буква) | (цифра)}
(буква) = (letter)
(цифра) = (digit)

(компонента переменной) = (индексированная переменная) | (обозначение поля)
(индексированная переменная) = (переменная-массив) '[' (выражение) {, (выражение)} ']'
(переменная-массив) = (переменная)

(обозначение поля) = (переменная-запись) . (имя поля)
(имя поля) = (имя)
(переменная-запись) = (переменная)
(выражение)=(простое выражение) [ (операция отношения) (простое выражение)]
