<программа> ::= program <имя> (<имя файла> {, <имя файла>}); <блок>.
<имя файла> ::= <имя>
<имя> ::= <буква> {<буква> | <цифра>}
<блок> ::= <раздел меток> <раздел констант> <раздел типов> <раздел переменных> <раздел
процедур и функций> <раздел операторов>
<раздел меток> ::= <пусто> | label <метка> {, <метка>};
<метка> ::= <целое без знака>
<раздел констант> ::= <пусто> |